FROM python:alpine3.8

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

ENV TEXT="Welcome to SCA Cloud School Application"

ENV DEBUG=false

ENV PORT=5000

COPY . /app

EXPOSE $PORT

ENTRYPOINT [ "python" ]

CMD [ "app.py" ]
